### ISSUE TITLE
Trying to Create an Automatic Command That Removes Entries That Are a Single Emoji

### ISSUE THREAD

**Issue by andrewcincotta** [hluk/copyq-commands#82] opened 2023-10-18 18:55 UTC
I use copyq on macOS and have a RayCast extension where I can search for emojis and paste them quickly. The problem is every time I paste an emoji, it copies it into my clipboard, causing unnecessary clutter. I'm looking to make an automatic command that checks newly added clipboard content for entries that contain only one emoji and nothing else (ex: '🧑🏼‍💻').

Can someone assist me in making this command? Thanks!
Pictures below:
<img width="756" alt="image" src="https://github.com/hluk/CopyQ/assets/116472178/d3b40137-d904-4b46-89d9-e743706cab06">
<img width="1206" alt="image" src="https://github.com/hluk/CopyQ/assets/116472178/674d34af-2713-4841-8d82-6331b8b2caa4">

**Comment by hluk** [comment] 2023-12-12 12:44
Duplicate of https://github.com/hluk/CopyQ/issues/2512.

**Closed by hluk** 2023-12-12 12:44 UTC
